### ISSUE TITLE
很白很简单,很喜欢,但是有个问题

### ISSUE THREAD

**Issue by ghost** [bieberg0n/bjdns#1]
用来测速的话,比如speedtest速度会狂掉,这会影响下载吗?上外网会不会被污染
发现上百度贴吧要VPN才能上，不然上不了

**Comment by bieberg0n** [comment]
是在Windows上遇到的问题吗

**Comment by ghost** [comment]
@bieberg0n 是的

**Comment by bieberg0n** [comment]
@JillCheng 
打包了新的Windows版，上贴吧和speedtest正常。
下载见：https://github.com/bieberg0n/bjdns/releases/download/v160306/bjdns_v160306.7z
你再测试下。

**Comment by ghost** [comment]
@bieberg0n 行了
