### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by meaverick** [bieberg0n/bjdns#2]
你好，有下列问题如何解决？谢谢
Traceback (most recent call last):
  File "bjdns.py", line 7, in <module>
    import requests
ImportError: No module named requests

Linux Tater-ARM 3.8.13.16 #6 SMP PREEMPT Thu Jan 22 11:45:22 CST 2015 armv7l GNU/Linux

**Comment by bieberg0n** [comment]
@meaverick 
sudo pip3 install --upgrade requests gevent

**Comment by meaverick** [comment]
Hi Robin
 感谢你的指点，py 顺利装到我PI2上并工作，防广告功能似乎工作很好，有一点delay,但是dns防污染似乎不起作用，我把py装到Raspberry pi2上，把路由的dns指向Raspberry pi2，开启了Tunnelbroker做IPV6隧道， Linux pi2 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

dig youtube.com

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53905
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;youtube.com.                   IN      A

;; ANSWER SECTION:
youtube.com.            190     IN      A       64.233.162.83

;; Query time: 4 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sun May 22 02:39:58 2016
;; MSG SIZE  rcvd: 45

dig youtube.com @208.67.220.220

youtube.com @208.67.220.220
; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> youtube.com @208.67.220.220
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44210
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;youtube.com.                   IN      A

;; ANSWER SECTION:
youtube.com.            2833    IN      A       93.46.8.89

;; Query time: 5 msec
;; SERVER: 208.67.220.220#53(208.67.220.220)
;; WHEN: Sun May 22 02:40:17 2016
;; MSG SIZE  rcvd: 56

**Comment by bieberg0n** [comment]
@meaverick 
 64.233.162.83是我手动指定的ip，用于在国内直连大部分的google服务(https://www.google.com.hk , https://www.youtube.com 等)。
被污染比较严重的有维基百科(https://zh.wikipedia.org )，可以作为测试。

**Comment by meaverick** [comment]
python 不能启动了不知为何
sudo python3 bjdns.py
